name: Approve
on:
  issue_comment:
    types: [created]

jobs:
  approve:
    if: >
      github.event.issue.pull_request &&
      contains(fromJSON(vars.ALLOWED_USER || '[]'), github.event.comment.user.login) &&
      contains(github.event.comment.body, vars.APPROVE_PHRASE)
    runs-on: ubuntu-latest
    steps:
      - name: Run release
        uses: ./.github/workflows/release.yml
        with:
          pr_number: ${{ github.event.issue.number }}